# Generated by Django 3.0.8 on 2020-08-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.CharField(max_length=25)),
                ('firstName', models.CharField(max_length=25)),
                ('emp_code', models.CharField(max_length=5)),
                ('mobile', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=25)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
    ]
